# Generated by Django 5.1.1 on 2024-10-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_be', '0002_tasks_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_be.tasks'),
        ),
    ]
