# Generated by Django 5.1.1 on 2024-10-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_be', '0003_tasks_parent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
