# Generated by Django 5.1.1 on 2024-10-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_be', '0004_alter_tasks_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='assigned_to',
            new_name='clients',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='status',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='parent_task',
            new_name='subtask',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='title',
        ),
        migrations.AddField(
            model_name='tasks',
            name='topic',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
    ]
