# Generated by Django 5.1.1 on 2024-10-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_be', '0005_rename_assigned_to_tasks_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='topic',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
