# Generated by Django 5.1.1 on 2024-10-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_be', '0007_remove_tasks_subtask_tasks_subtasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='contacts',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
