# Generated by Django 5.1.1 on 2024-10-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_be', '0009_rename_email_contacts_mail_contacts_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='join_be.users'),
        ),
    ]
