# Generated by Django 5.1.1 on 2024-10-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_be', '0010_alter_contacts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
