# Generated by Django 5.1.1 on 2024-10-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_be', '0011_remove_tasks_due_date_alter_tasks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
