# Generated by Django 5.1.1 on 2024-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_be', '0012_alter_tasks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
